replicaCount: 0
securityContext:
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false
  runAsNonRoot: true
resources:
  requests:
    memory: 2048Mi
    cpu: 800m
  limits:
    memory: 8192Mi
    cpu: 970m
strategyType: RollingUpdate
podSecurityContext:
  runAsNonRoot: true

minecraftServer:
  eula: "true"
  type: "VANILLA"
  version: "LATEST"
  memory: "6G"
  difficulty: "easy"
  gameMode: survival
  maxPlayers: 3
  motd: "Welcome to the Family Server!"
  serviceType: ClusterIP

persistence:
  dataDir:
    enabled: true
    size: 100Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: "local-path"

extraDeploy:
  - |
    apiVersion: traefik.io/v1alpha1
    kind: IngressRouteTCP
    metadata:
      name: minecraft-tcp
      namespace: minecraft
    spec:
      entryPoints:
        - minecraft
      routes:
      - match: HostSNI(`*`)
        services:
        - name: minecraft
          port: 25565
